apiVersion: apps/v1
kind: Deployment
metadata:
  name: rxp-web
  namespace: ruralxperience
  labels:
    app: rxp-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rxp-web
  template:
    metadata:
      labels:
        app: rxp-web
    spec:
      containers:
        - name: rxp-web
          image: ayoubtec/rxp-web:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 15
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
