apiVersion: v1
kind: ConfigMap
metadata:
  name: rxp-config
  namespace: ruralxperience
data:
  POSTGRES_DB: ruralxperience
  POSTGRES_USER: rxp_user
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-svc:5432/ruralxperience
  SPRING_DATASOURCE_USERNAME: rxp_user
  SPRING_REDIS_HOST: redis-svc
  SPRING_REDIS_PORT: "6379"
  SPRING_MAIL_HOST: mailhog-svc
  SPRING_MAIL_PORT: "1025"
  JWT_SECRET: 7p6E/R8WvL2N4mZ+7Q9Y3uX1A5S8D0F2G4H6J8K0L2M=
  CORS_ORIGINS: http://rxp-web-svc:4200
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "false"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "false"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_REQUIRED: "false"