
-- ── Audit logs ───────────────────────────────────────────────────

INSERT INTO audit_logs (admin_id, admin_email, action, entity_type, entity_id, details, ip_address) VALUES
                                                                                                        (1, 'admin@ruralxperience.com', 'EXPERIENCE_APPROVED',  'Experience', 1,  'Approved: Lavender Harvest in Provence',        '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'EXPERIENCE_APPROVED',  'Experience', 2,  'Approved: Truffle Hunting in Périgord',         '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'EXPERIENCE_REJECTED',  'Experience', 3,  'Rejected: insufficient description quality',   '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'EXPERIENCE_APPROVED',  'Experience', 4,  'Approved: Alpine Cheese Making Workshop',       '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'EXPERIENCE_REJECTED',  'Experience', 5,  'Rejected: missing safety information',         '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'USER_SUSPENDED',       'User',       3,  'Suspended: repeated policy violations',        '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'USER_ENABLED',         'User',       3,  'Re-enabled after appeal review',               '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'USER_ROLE_CHANGED',    'User',       5,  'EXPLORER → HOST after host verification',      '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'USER_ROLE_CHANGED',    'User',       6,  'EXPLORER → HOST after host verification',      '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'EXPERIENCE_APPROVED',  'Experience', 7,  'Approved: Oyster Farming in Brittany',         '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'EXPERIENCE_APPROVED',  'Experience', 8,  'Approved: Vineyard Harvest Weekend',           '192.168.1.1'),
                                                                                                        (1, 'admin@ruralxperience.com', 'USER_SUSPENDED',       'User',       7,  'Suspended: fraudulent booking reports',        '192.168.1.2'),
                                                                                                        (1, 'admin@ruralxperience.com', 'EXPERIENCE_REJECTED',  'Experience', 9,  'Rejected: price does not match description',   '192.168.1.2'),
                                                                                                        (1, 'admin@ruralxperience.com', 'USER_ROLE_CHANGED',    'User',       8,  'EXPLORER → HOST after host verification',      '192.168.1.2'),
                                                                                                        (1, 'admin@ruralxperience.com', 'EXPERIENCE_APPROVED',  'Experience', 10, 'Approved: Beekeeping Experience in Burgundy',  '192.168.1.2');